spring.application.name=toyproject4-team4

# MySQL DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/kabojago
spring.datasource.username=root
spring.datasource.password=1234

# JPA (Hibernate Dialect)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect